export const TOTALSCORE = 'TOTALSCORE';
export const MATCHINGITEM = 'MATCHINGITEM';
export const ISFIRSTINSTALL = 'ISFIRSTINSTALL';
export const NOTIFICATIONCOUNT = 'NOTIFICATIONCOUNT';
export const MESSAGECOUNT = 'MESSAGECOUNT';
export const REMEMBERME = 'REMEMBERME';

