const Images = {

  // Botoom Tab Images
  homeactive: require('../Images/BottomTab/homeactive.png'),
  homeinactive: require('../Images/BottomTab/homeinactive.png'),
  listactive: require('../Images/BottomTab/listactive.png'),
  listinactive: require('../Images/BottomTab/listinactive.png'),
  additemactive: require('../Images/BottomTab/additemactive.png'),
  additeminactive: require('../Images/BottomTab/additeminactive.png'),
  messageactive: require('../Images/BottomTab/messageactive.png'),
  messageinactive: require('../Images/BottomTab/messageinactive.png'),
  profileactive: require('../Images/BottomTab/profileactive.png'),
  profileinactive: require('../Images/BottomTab/profileinactive.png'),
  logoColor: require('../Images/logoColor.png'),
  HeaderBackarow: require('../Images/HeaderBackarow.png'),
  logoSimple: require('../Images/logoSimple.png'),
  logoBranding: require('../Images/logoBranding.png'),
  facebookIcon: require('../Images/facebookIcon.png'),
  googleIcon: require('../Images/googleIcon.png'),
  verticaldot: require('../Images/verticaldot.png'),
  togolon: require('../Images/togolon.png'),
  togoloff: require('../Images/togoloff.png'),
  rightarrow: require('../Images/rightarrow.png'),
  addProfilePic: require('../Images/addProfilePic.png'),
  close: require('../Images/close.png'),
  swipeCircleTick: require('../Images/swipeCircleTick.png'),
  swipeCircleCross: require('../Images/swipeCircleCross.png'),
  addphoto: require('../Images/addphoto.png'),
  verifayEmail: require('../Images/verifayEmail.png'),
  welcome: require('../Images/welcome.png'),
  passshow: require('../Images/passshow.png'),
  passhide: require('../Images/passhide.png'),
  tickcheck: require('../Images/tickcheck.png'),
  location: require('../Images/location.png'),
  tick: require('../Images/tick.png'),
  radioactive: require('../Images/radioactive.png'),
  radioinactive: require('../Images/radioinactive.png'),
  emptyitem: require('../Images/emptyitem.png'),
  calander: require('../Images/calander.png'),
  activeCheck: require('../Images/activeCheck.png'),
  unactivecheck: require('../Images/unactivecheck.png'),

};
export default Images;

